### PR TITLE
fix: Log event via object mapper and not depend on toString

### LINKED ISSUE #112: Log events of logging module does not always logs entire event
Using log event feature of @PowetrtoolsLogging. 

## Expected Behavior
When logging S3EventNotification, it should log payload.

## Current Behavior
Does not logs payload but rather just Object Hash

## Possible Solution
Use object mapper to parse the object instead of depending on toString implementation on POJO.

## Steps to Reproduce (for bugs)

Handler like:

```
   @PowertoolsLogging(logEvent = true)
    public IndexFacesResponse handleRequest(S3EventNotification input, Context context) {
```

Logs `message
com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification@`

## Environment

* **Powertools version used**: 0.3.1-beta
* **Packaging format (Layers, Maven/Gradle)**: Both
* **AWS Lambda function runtime:** java8
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

### PR DESCRIPTION
**Pull request by pankajagrawal16**
**Issue #, if available:**

Closes #112 

## Description of changes:

Log events via object mapper.

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics]()

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java [hunk 1]
```diff
@@ -181,14 +186,24 @@ private double samplingRate(final PowertoolsLogging powertoolsLogging) {
...
+
     private Logger logger(final ProceedingJoinPoint pjp) {
         return LogManager.getLogger(pjp.getSignature().getDeclaringType());
     }
 
     private static Optional<String> getXrayTraceId() {
         final String X_AMZN_TRACE_ID = getenv("_X_AMZN_TRACE_ID");
         if(X_AMZN_TRACE_ID != null) {
-            return ofNullable(X_AMZN_TRACE_ID.split(";")[0].replace("Root=", ""));
+            return of(X_AMZN_TRACE_ID.split(";")[0].replace("Root=", ""));
```
Comment (msailes) [inline powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java:206]: Was this intentional?

Comment (pankajagrawal16) [reply powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java:206]: Yeah it just resolves a warning from compiler, since it was wrapping a statement which can never be null into `ofNullable `

**Review by msailes — APPROVED** [review]
Approved
